# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: eduardocabrera
# "service" is the name of this project. This will also be added to your AWS resource names.
service: appointment-medic

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: dev
  memorySize: 512
  timeout: 10
  environment:
    DYNAMODB_TABLE_NAME: ${cf:appointment-cdk.AppointmentsTableName}
    SNS_TOPIC_ARN: ${cf:appointment-cdk.AppointmentTopicArn}
    EVENT_BUS_NAME: ${cf:appointment-cdk.AppointmentEventBusName}
    DB_ENDPOINT: ${cf:appointment-cdk.AppointmentDbEndpoint}
    DB_PORT: ${cf:appointment-cdk.AppointmentDbPort}
    DB_NAME: ${cf:appointment-cdk.AppointmentDbName}
    DB_SECRET_ARN: ${cf:appointment-cdk.AppointmentDbSecretArn}
    QUEUE_COMPLETED_ARN: ${cf:appointment-cdk.BackupQueueArn}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - secretsmanager:GetSecretValue
          Resource: ${cf:appointment-cdk.AppointmentDbSecretArn}

functions:
  appointment:
    handler: src/handlers/appointment.handler
    events:
      - http:
          path: appointment
          method: post
      - http:
          path: appointment/{insuredId}
          method: get
      - sqs:
          arn: ${cf:appointment-cdk.BackupQueueArn}

  appointment_pe:
    handler: src/handlers/appointment_pe.handler
    events:
      - sqs:
          arn:
            Fn::Join:
              - ':'
              - - 'arn:aws:sqs'
                - ${self:provider.region}
                - ${aws:accountId}
                - ''
                - ${cf:appointment-cdk.QueuePEName}

  appointment_cl:
    handler: src/handlers/appointment_cl.handler
    events:
      - sqs:
          arn:
            Fn::Join:
              - ':'
              - - 'arn:aws:sqs'
                - ${self:provider.region}
                - ${aws:accountId}
                - ''
                - ${cf:appointment-cdk.QueueCLName}

plugins:
  - serverless-esbuild

package:
  individually: true

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude: ['aws-sdk']
    target: 'node18'
    platform: 'node'
    concurrency: 10
