# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: eduardocabrera
# "service" is the name of this project. This will also be added to your AWS resource names.
service: appointment-medic

frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: dev
  memorySize: 512
  timeout: 10
  environment:
    DYNAMODB_TABLE_NAME: ${cf:AppointmentCdkStack.AppointmentsTableName}
    SNS_TOPIC_ARN: ${cf:AppointmentCdkStack.AppointmentTopicArn}
    EVENT_BUS_NAME: ${cf:AppointmentCdkStack.AppointmentEventBusName}
    DB_ENDPOINT: ${cf:AppointmentCdkStack.AppointmentDbEndpoint}
    DB_PORT: ${cf:AppointmentCdkStack.AppointmentDbPort}
    DB_NAME: ${cf:AppointmentCdkStack.AppointmentDbName}
    DB_SECRET_ARN: ${cf:AppointmentCdkStack.AppointmentDbSecretArn}
    QUEUE_COMPLETED_ARN: ${cf:AppointmentCdkStack.BackupQueueArn}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - secretsmanager:GetSecretValue
          Resource: ${cf:AppointmentCdkStack.AppointmentDbSecretArn}
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:Query
            - dynamodb:UpdateItem
            - dynamodb:GetItem
          Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${cf:AppointmentCdkStack.AppointmentsTableName}
        - Effect: Allow
          Action:
            - sns:Publish
          Resource: ${cf:AppointmentCdkStack.AppointmentTopicArn}

functions:
  appointment:
    handler: src/handlers/appointmentHandler.handler
    events:
      - http:
          path: appointment
          method: post
      - http:
          path: appointment/{insuredId}
          method: get
      - sqs:
          arn: ${cf:AppointmentCdkStack.BackupQueueArn}

  appointment_pe:
    handler: src/handlers/appointmentPeHandler.handler
    events:
      - sqs:
          arn: ${cf:AppointmentCdkStack.QueuePEName}
    iam:
      role:
        statements:
          Action:
            - events:PutEvents
          Resource: arn:aws:events:${self:provider.region}:*:event-bus/${cf:AppointmentCdkStack.AppointmentEventBusName}

  appointment_cl:
    handler: src/handlers/appointmentClHandler.handler
    events:
      - sqs:
          arn: ${cf:AppointmentCdkStack.QueueCLName}
    iam:
      role:
        statements:
          Action:
            - events:PutEvents
          Resource: arn:aws:events:${self:provider.region}:*:event-bus/${cf:AppointmentCdkStack.AppointmentEventBusName}

package:
  individually: false
