// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "Documentation Appointment API",
    "version": "1"
  },
  "paths": {
    "/appointment": {
      "post": {
        "summary": "appointment",
        "description": "",
        "operationId": "appointment.post.appointment",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/appointment/{insuredId}": {
      "get": {
        "summary": "appointment",
        "description": "",
        "operationId": "appointment.get.appointment/{insuredId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "insuredId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {
    "AppointmentInput": {
      "properties": {
        "insuredId": {
          "title": "AppointmentInput.insuredId",
          "description": "Código del asegurado (5 dígitos, puede tener ceros al inicio)",
          "examples": "\"00001\"",
          "type": "string"
        },
        "scheduleId": {
          "title": "AppointmentInput.scheduleId",
          "description": "Identificador del horario para la cita",
          "examples": "123",
          "type": "number"
        },
        "countryISO": {
          "enum": [
            "PE",
            "CL"
          ],
          "title": "AppointmentInput.countryISO",
          "description": "Código del país",
          "examples": "\"PE\"",
          "type": "string"
        }
      },
      "required": [
        "insuredId",
        "scheduleId",
        "countryISO"
      ],
      "additionalProperties": false,
      "title": "AppointmentInput",
      "type": "object"
    },
    "Appointment": {
      "properties": {
        "appointmentId": {
          "title": "Appointment.appointmentId",
          "description": "ID de la cita generada automáticamente",
          "examples": "\"00001-1716143456789\"",
          "type": "string"
        },
        "insuredId": {
          "title": "Appointment.insuredId",
          "description": "Código del asegurado",
          "examples": "\"00001\"",
          "type": "string"
        },
        "scheduleId": {
          "title": "Appointment.scheduleId",
          "description": "ID del horario",
          "examples": "456",
          "type": "number"
        },
        "countryISO": {
          "enum": [
            "PE",
            "CL"
          ],
          "title": "Appointment.countryISO",
          "description": "País de origen",
          "examples": "\"CL\"",
          "type": "string"
        },
        "status": {
          "enum": [
            "pending",
            "completed"
          ],
          "title": "Appointment.status",
          "description": "Estado de la cita",
          "examples": "\"pending\"",
          "type": "string"
        }
      },
      "required": [
        "appointmentId",
        "insuredId",
        "scheduleId",
        "countryISO",
        "status"
      ],
      "additionalProperties": false,
      "title": "Appointment",
      "type": "object"
    }
  },
  "securityDefinitions": {}
};